### PR TITLE
[debian] Make PostgreSQL server suggested, not required

### LINKED ISSUE #141: [debian] Drop dependency on PostgreSQL package
You don't need a PostgreSQL package installed on the system in order to use linz-bde-uploader.
The database could be remote, so we only need the libpq client here (indirectly, via perl).

Right now PostgreSQL package is required both directly and indirectly via other dependencies like postgresql-tableversion. Those dependencies should also be dropped as they are really only dependencies for the target database.

Things may change now that we have the schema-loader script, for that one, we do need parts of tableversion, specifically the non-extension side of it, but at the moment tableversion package is a single one so we cannot distinguish between the two.

For the sake of this ticket, it's enough to drop the _explicit_ (direct) dependency on PostgreSQL server, the rest will be dealt with by separate tickets to the relevant packages.

### PR DESCRIPTION
**Pull request by strk**
Fixes #141

### CODE REVIEW

**Comment by imincik** [comment]
@strk , I can't believe that it is that simple to drop that PG dependency. If this would be the only thing to do it would be already done :).

Or the reason why PG is installed on BDE Processor might be that it is dependency of other BDE Processor packages as well and needs to be removed from them as well. Our ultimate goal is to prevent having PG on BDE Processor machine. Would you please test it ?

**Comment by strk** [comment]
I believe it is only tableversion that needs love, the other packages should be fine already.
See https://github.com/linz/postgresql-tableversion/issues/95

**Comment by imincik** [comment]
You might be right

**Comment by imincik** [comment]
I approved this PR, but would you please have a look on all other packages which are needed to be changed to drop PG dependency ?

**Pull request merged**
