### PR TITLE
[2.5 backport] Force UTF8 decoding of BDE data stream

### LINKED ISSUE #210: UTF8 characters in BDE files are mungled when sent to PostgreSQL
This is the case since we started using `pg_copydata`, that is from version 2.4.0.
Needs to be fixed in 2.5 and master branches.
PR for master branch is #209 while backport to 2.5 is coming.

### PR DESCRIPTION
**Pull request by strk**
Backport of PR #209
Fixes #210 for 2.5 branch

### CODE REVIEW

**Comment by palmerj** [comment]
Are we also going to backport d006566?

**Comment by strk** [comment]
The test did not apply cleanly, not sure it is worth it

**Comment by palmerj** [comment]
> The test did not apply cleanly, not sure it is worth it
We need a unit test for UTF8 I think. Why did it not apply to the release-2.5 branch?

**Comment by strk** [comment]
Test was now backported too, merging.

**Pull request merged**
