### PR TITLE
Fix swapped inserts/deletes counts in upload stats

### PR DESCRIPTION
**Pull request by strk**
See #165

TODO:
  - [x] Fix swapped insert/delete counts
  - [x] Update swapped counts in existing data
  - [x] Add tests

### CODE REVIEW

**Comment by strk** [comment]
I don't feel fully comfortable with automatic swapping ninserts/ndeletes in existing databases because there's no easy way to tell if they are swapped or not, other than checking the version of `linz-bde-uploader`.
The risk is to undo some manually performed fix. Or we could verify with `table_version` if the counts match. What do you think ?

I confirm the test I was running to compare table_version and stats view on the matter passes after running:

> update bde_control.upload_stats set ninsert = ndelete, ndelete = ninsert;

on the database created during testing of current production versions of components

**Comment by strk** [comment]
With 61e1e2e710930d96d72791c34f9d84c8e0a448f7 I've used a patch. Should work effectively.

**Comment by palmerj** [comment]
> I don't feel fully comfortable with automatic swapping ninserts/ndeletes in existing databases because there's no easy way to tell if they are swapped or not, other than checking the version of linz-bde-uploader.
The risk is to undo some manually performed fix. Or we could verify with table_version if the counts match. What do you think ?

Create a SQL patch to do it if the version is less than or equal to the version we know it has not been fixed in?

**Comment by palmerj** [comment]
> I've added one test, but while adding a second one I found out that a run with -full using a second dataset with the same 3 records in it results in registering 3 inserts and 3 deletes (and no updates). Why is this ? Is it revealing another bug ?

From memory I think running `-full` will clean the table and reload the data again. Could this be the case?

**Comment by strk** [comment]
NOTE so self: the patch fixing swapping is wrong as it swapping all records while it should only swap those coming from level5

**Comment by strk** [comment]
found the problem with stats not being updated: target table NOT being versioned !
In the test, I'm not enabling table versioning, not to depend on it. Will do.

**Comment by strk** [comment]
Enabling versioning on the target table makes no difference, there is really NO update performed on the table. The logs say:
```
2018/10/15 17:20:41 DEBUG> BdeDatabase.pm:762 - analyzing "pg_temp_2.crs_parcel_bndry"
2018/10/15 17:20:41 DEBUG> BdeDatabase.pm:762 - "crs_parcel_bndry": scanned 1 of 1 pages, containing
 2 live rows and 0 dead rows; 2 rows in sample, 2 estimated total rows
2018/10/15 17:20:41 INFO> BdeDatabase.pm:762 - Preparing incremental change table
2018/10/15 17:20:41 DEBUG> BdeDatabase.pm:762 - building index "_inc_tbl_id" on table "_incremental"
2018/10/15 17:20:41 DEBUG> BdeDatabase.pm:762 - analyzing "pg_temp_2._incremental"
2018/10/15 17:20:41 DEBUG> BdeDatabase.pm:762 - "_incremental": scanned 0 of 0 pages, containing 0 l
ive rows and 0 dead rows; 0 rows in sample, 0 estimated total rows
2018/10/15 17:20:41 INFO> BdeDatabase.pm:762 - Selecting incremental records
2018/10/15 17:20:41 DEBUG> BdeDatabase.pm:762 - table "_tmp_inc_change" does not exist, skipping
2018/10/15 17:20:41 INFO> BdeDatabase.pm:762 - There are no changes to apply for crs_parcel_bndry
```

I've modified the code to save the temporary table in a persistent table for inspection.
Here's how the temporary (uploaded) table and the previous table look like:
```
linz_bde_uploader_test_10354=# select * from public.xxxx; 
 pri_id  | sequence |  lin_id  | reversed | audit_id 
 ---------+----------+----------+----------+---------- 
 4457328 |       10 | 29694591 | Y        |      100 
 4457326 |        3 | 11960041 | Y        |        0 
 (2 rows) 
 linz_bde_uploader_test_10354=# select * from bde.crs_parcel_bndry ; 
 pri_id  | sequence |  lin_id  | reversed | audit_id 
 ---------+----------+----------+----------+---------- 
 4457328 |        1 | 29694591 | Y        |      100 
17:21 strk 4457327 |        2 | 29694578 | N        |      200 
17:21 strk (2 rows) 

```

I don't undertand how the code can say there are no incremental changes there. Any idea @palmerj ?

The tables.conf file has:
```
TABLE crs_parcel_bndry key=audit_id  row_tol=0.20,0.95 files test_file
```

**Comment by strk** [comment]
I *think* I got it... there's a special record that is supposed to be in tables.conf, that I'm not adding, which is the `l5_change_table` one. I wonder if linz_bde_uploader should give more feedback when such record is missing in tables.conf, or also I wonder how many other ways exist to support an incremental upgrade... All of this should be documented somewhere, not sure where though as it doesn't look like something about BDE store itself, but rather something about linz_bde_uploader configuration ?

**Comment by palmerj** [comment]
> I wonder if linz_bde_uploader should give more feedback when such record is missing in tables.conf, or also I wonder how many other ways exist to support an incremental upgrade... 

Yes that would be good, even better if the warning only comes if linz_bde_uploader is in incremental update mode.

> All of this should be documented somewhere, not sure where though as it doesn't look like something about BDE store itself, but rather something about linz_bde_uploader configuration ?

It's documented https://github.com/linz/linz_bde_uploader/blob/master/conf/tables.conf#L28 at the moment. Feel free to add to other places you see fit.

**Comment by palmerj** [comment]
The CI tests are failing at the moment

**Comment by strk** [comment]
> It's documented https://github.com/linz/linz_bde_uploader/blob/master/conf/tables.conf#L28 at the moment. Feel free to add to other places you see fit.

I meant documentation of the format of the so-called "change table": which fields are expected to be found in that table, what is their semantic etc. I'll try to figure it out and write some more as I learn

**Comment by strk** [comment]
I'm finally happy with the code. Now I have it fully covered with a test and confirm that reverting the commit which introduces the fix triggers a test failure:
```
#   Failed test 'upload_stats[13].ninsert'
#   at t/linz_bde_uploader.t line 1064.
#          got: '1'
#     expected: '3'

#   Failed test 'upload_stats[13].ndelete'
#   at t/linz_bde_uploader.t line 1065.
#          got: '3'
#     expected: '1'
```

I've squashed some commits and rebased to master so previous commit references might not be working anymore. I did add documentation for the format of the `changetable` (which columns having which semantic), included in this PR.

@palmerj if you want to give a final look it'd be great to have this finished before you leave :)

@imincik once this is approved, do you think it makes any sense to backport to the old-generation repo ? (I don't think it does).

**Comment by imincik** [comment]
> @imincik once this is approved, do you think it makes any sense to backport to the old-generation repo ? (I don't think it does).

I don't think we should backport this to old-gen.

**Comment by strk** [comment]
For some reason Travis runs 282 tests instead of 283:
```
Parse errors: Bad plan.  You planned 283 tests but ran 282.
Files=1, Tests=282,  7 wallclock secs ( 0.06 usr  0.00 sys +  4.44 cusr  0.54 csys =  5.04 CPU)
Result: FAIL
```

Weird, as on my system all of 283 are run:
```
All tests successful.
Files=1, Tests=283,  8 wallclock secs ( 0.04 usr  0.00 sys +  4.08 cusr  0.64 csys =  4.76 CPU)
Result: PASS
```

**Comment by strk** [comment]
For some reason Travis runs 282 tests instead of 283:
```
Parse errors: Bad plan.  You planned 283 tests but ran 282.
Files=1, Tests=282,  7 wallclock secs ( 0.06 usr  0.00 sys +  4.44 cusr  0.54 csys =  5.04 CPU)
Result: FAIL
```

Weird, as on my system all of 283 are run:
```
All tests successful.
Files=1, Tests=283,  8 wallclock secs ( 0.04 usr  0.00 sys +  4.08 cusr  0.64 csys =  4.76 CPU)
Result: PASS
```

**Comment by strk** [comment]
For some reason Travis runs 282 tests instead of 283:
```
Parse errors: Bad plan.  You planned 283 tests but ran 282.
Files=1, Tests=282,  7 wallclock secs ( 0.06 usr  0.00 sys +  4.44 cusr  0.54 csys =  5.04 CPU)
Result: FAIL
```

Weird, as on my system all of 283 are run:
```
All tests successful.
Files=1, Tests=283,  8 wallclock secs ( 0.04 usr  0.00 sys +  4.08 cusr  0.64 csys =  4.76 CPU)
Result: PASS
```

I'm running perl 5.26.1, Travis is running 5.20.3

**Comment by strk** [comment]
For some reason Travis runs 282 tests instead of 283:
```
Parse errors: Bad plan.  You planned 283 tests but ran 282.
Files=1, Tests=282,  7 wallclock secs ( 0.06 usr  0.00 sys +  4.44 cusr  0.54 csys =  5.04 CPU)
Result: FAIL
```

Weird, as on my system all of 283 are run:
```
All tests successful.
Files=1, Tests=283,  8 wallclock secs ( 0.04 usr  0.00 sys +  4.08 cusr  0.64 csys =  4.76 CPU)
Result: PASS
```

I'm running perl 5.26.1, Travis is running 5.20.3

Will enable travis testing in verbose mode

**Comment by strk** [comment]
For some reason Travis runs 282 tests instead of 283:
```
Parse errors: Bad plan.  You planned 283 tests but ran 282.
Files=1, Tests=282,  7 wallclock secs ( 0.06 usr  0.00 sys +  4.44 cusr  0.54 csys =  5.04 CPU)
Result: FAIL
```

Weird, as on my system all of 283 are run:
```
All tests successful.
Files=1, Tests=283,  8 wallclock secs ( 0.04 usr  0.00 sys +  4.08 cusr  0.64 csys =  4.76 CPU)
Result: PASS
```

I'm running perl 5.26.1, Travis is running 5.20.3

Will enable travis testing in verbose mode

**Comment by strk** [comment]
It looks like Travis was self-fixed somehow, now tests pass. So this is ready for review/merge.

**Comment by strk** [comment]
Taking it back, we had a false negative (false success) due to a broken "make check" rule. Now I fixed it, let's see if the tests count mismatch is back

**Comment by strk** [comment]
Ok we're back to difference in counts.
The difference is that on my system this is run:
ok 61 - sourcing /usr/share/linz-bde-schema/sql/06-schema_comments.sql gives no error
While on Travis it is not. I guess it depends on the _version_ of linz-bde-schema being installed, because the code uses globs to source _all_ of scripts in bdeschema sqldir.

Travis is installing version 1.0.2 of `linz-bde-schema` while comments were introduced in version 1.1.0.
I don't see any reason why we should be installing those packages from tags rather than from packages, btw. Do you @imincik ? The other components are all installing packages from packagecloud so I guess I'll do the same in this PR too

**Comment by strk** [comment]
Ah now I see, we didn't install from packages because packages have dependencies on strong versions of postgresql/postgis, making us stuck on using them. I will just upgrade the dependency of linz-bde-schema from 1.0.2 to 1.2.1

**Comment by strk** [comment]
ok, that did it. So this is ready for review and merge.

**Comment by strk** [comment]
@palmerj how about merging this  ? Any reason not to ?

**Pull request merged**
