### PR TITLE
Set version and release date for 2.5.0

### PR DESCRIPTION
**Pull request by strk**
For the win!

### CODE REVIEW

**Comment by strk** [comment]
Let's wait before merging this, a new issue came out about supporting newer table_version, which prevents dropping versioned tables (we need to modify code in here to first unversion and then drop)

**Comment by strk** [comment]
The bug was fixed, now let's just give Travis a chance to run integration testing (bde-processor-deployment) before merging

**Comment by strk** [comment]
Travis still fails:
> ERROR:  Level 0 update of table crs_appellation from dataset 20150606233300 failed in Dropping current version of the table crs_appellation. Error: cannot drop table crs_appellation because other objects depend on it at /usr/share/perl5/LINZ/BdeDatabase.pm line 726.

I fail to understand this now. Supposedly Travis installed linz-bde-uploader revision `a84a838ee1a458678158783d320a61f6a49518f6`, which does contain the fix for the above error.

Unfortunately the function that prints database component versions doesn't give the detail of git hash, just prints '2.6.0dev' for bde-uploader

**Comment by strk** [comment]
Figured, with debug build.
The problem is that:
> function bde.bde_get_app_specific(bde.crs_appellation,character) depends on type bde.crs_appellation

That is, we STILL need the CASCADE to drop `bde.crs_appellation`.
But this reveals another big issue (to me) -- that is, the very first time we upload a BDE dataset, that is when we use `DROP` for tables being replaced, we end up dropping a function !!

**Comment by imincik** [comment]
This task is still relevant.

**Comment by strk** [comment]
With #183 merged I thinks it's fine to go on with the release. This PR needs to be rebased though, to make sure we don't miss any NEWS item

**Comment by strk** [comment]
The test is failing because it suffers from a race condition: comments are added to each of the installed functions to mention the timestamp in which they were installed. As we're installing two times, we get two different timestamps, which is seen as a difference. 

This "timestamping" happens in `sql/02-bde_control_functions.sql.in`, using up-to-the minute as resolution

I've now committed a change that makes that test immune, replacing installation timestamp with a fake value, let's see how it goes.

**Pull request merged**
