### PR TITLE
Add stdout support to schema loader

### PR DESCRIPTION
**Pull request by strk**
See #175

### CODE REVIEW

**Comment by strk** [comment]
This is ready for review. Will be needed to proceed with linz-lds-bds-schema loader

**Comment by palmerj** [comment]
Hi @strk can we please have some tests for the PR?

**Comment by strk** [comment]
The script is already tested with the calling convention using database name, which is thus guaranteed to work under Travis environment.

Now I've added tester for stdout it clearly shows you'll get an error unless you use a newer table_version, supporting stdout loading. It's good to have such test too, so I guess we'll want Travis to use a matrix to test both older and newer table_version.

Note that old table_version still works fine when NOT requesting stdout loader, in which case the linz-bde-uploader-schema-load script just prints a WARNING about the operations not being transactional (will be transactional when table_version supports stdout loading)

**Comment by strk** [comment]
Well I'm actually trying another approach: using matrix entries to have Travis test BOTH the supported and non-supported versions of table_version. Let's see how it goes.

**Comment by strk** [comment]
A reason NOT to automatically install linz-bde-schema is that we don't know if the user wants or not to version all tables, and to create indices (`linz-bde-schema-load` has options for that)

**Comment by strk** [comment]
Alright, we finally have test for stdout support (and the non-stdout version as well).
We could increase testing coverage by having more combinations but for now we have:
  - Perl 5.12,  PostgreSQL 9.3, PostGIS 2.2, NON stdout
  - Perl 5.18,  PostgreSQL 9.3, PostGIS 2.2, NON stdout
  - Perl 5.2,  PostgreSQL 9.4, PostGIS 2.3, NON stdout
  - Perl 5.22,  PostgreSQL 9.5, PostGIS 2.3, NON stdout
  - Perl 5.2,  PostgreSQL 9.6, PostGIS 2.3, NON stdout
  - Perl 5.24,  PostgreSQL 9.6, PostGIS 2.3, STDOUT

Ready to merge @palmerj ?

**Pull request merged**
